<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PlatformTarget>x86</PlatformTarget>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
		<Title>Pure3D Data Viewer Plugin API Memory Tunnel</Title>
		<Authors>Proddy</Authors>
		<Company>Donut Team</Company>
		<Product>Pure3D Data Viewer</Product>
		<Description>A helper app to create an IPC tunnel to communicate with SHARMemory.</Description>
		<Copyright>Donut Team 2025</Copyright>
		<ApplicationIcon>256x256.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="256x256.ico" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\external\SHARMemory\SHARMemory\SHARMemory\SHARMemory.csproj" />
	  <ProjectReference Include="..\Pure3DDataViewerPluginAPI\Pure3DDataViewerPluginAPI.csproj" />
	</ItemGroup>

</Project>
