using CarPhysicsObjectGenerator.Forms;
using CarPhysicsObjectGenerator.Helpers;
using NetP3DLib.P3D;
using NetP3DLib.P3D.Chunks;
using Pure3DDataViewerPluginAPI;
using Pure3DDataViewerPluginAPI.Enums;
using Pure3DDataViewerPluginAPI.Interfaces;
using System.Reflection;

namespace CarPhysicsObjectGenerator.Handlers;
public class GeneratePhysicsObject : IFileHandler
{
    public string Name => "Generate Physics Object";

    public Image? Image => CarPhysicsObjectGeneratorPlugin.CreateImage;

    public static bool AddHistoryChunk
    {
        get => RegistryUtils.GetBoolean("CarPhysicsObjectGeneratorAddHistoryChunk", true)!.Value;
        set => RegistryUtils.SetBoolean("CarPhysicsObjectGeneratorAddHistoryChunk", value);
    }

    public static bool RemoveExisting
    {
        get => RegistryUtils.GetBoolean("CarPhysicsObjectGeneratorRemoveExisting", true)!.Value;
        set => RegistryUtils.SetBoolean("CarPhysicsObjectGeneratorRemoveExisting", value);
    }

    public IList<(string Name, bool Value)>? GetSettings() => [
        ( "Add History Chunk", AddHistoryChunk ),
        ( "Remove Existing Physics Object", RemoveExisting ),
    ];

    public void SetSetting(string name, bool value)
    {
        switch (name)
        {
            case "Add History Chunk":
                AddHistoryChunk = value;
                break;
            case "Remove Existing Physics Object":
                RemoveExisting = value;
                break;
            default:
                MessageBox.Show($"Unsupported setting name: {name}", Name, MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
        }
    }

    public FileCallbackResult Handle(P3DFile p3dFile)
    {
        var compositeDrawables = p3dFile.GetChunksOfType<CompositeDrawableChunk>();
        if (compositeDrawables.Count == 0)
        {
            MessageBox.Show($"Could not find any Composite Drawable chunks in file.", Name, MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return FileCallbackResult.Unchanged;
        }

        CompositeDrawableChunk compositeDrawable;
        if (compositeDrawables.Count == 1)
        {
            compositeDrawable = compositeDrawables[0];
        }
        else
        {
            using var selectCompositeDrawable = new FrmSelectCompositeDrawable([.. compositeDrawables]);
            if (selectCompositeDrawable.ShowDialog() != DialogResult.OK)
            {
                MessageBox.Show("Multiple composite drawables and none selected. Nothing changed.", Name, MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return FileCallbackResult.Unchanged;
            }
            compositeDrawable = selectCompositeDrawable.Value;
        }
        var carName = compositeDrawable.Name;
        var skeletonName = compositeDrawable.SkeletonName;

        var skeleton = p3dFile.GetFirstChunkOfType<SkeletonChunk>(skeletonName);
        if (skeleton == null)
        {
            MessageBox.Show($"Could not find Skeleton chunk with name: {skeletonName}.", Name, MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return FileCallbackResult.Unchanged;
        }
        var skeletonBV = p3dFile.GetFirstChunkOfType<SkeletonChunk>($"{skeletonName}BV") ?? skeleton;

        var collisionObject = p3dFile.GetFirstChunkOfType<CollisionObjectChunk>(skeletonName);
        if (collisionObject == null)
        {
            MessageBox.Show($"Could not find Collision Object chunk with name: {skeletonName}.", Name, MessageBoxButtons.OK, MessageBoxIcon.Warning);
            return FileCallbackResult.Unchanged;
        }
        var collisionObjectBV = p3dFile.GetFirstChunkOfType<CollisionObjectChunk>($"{skeletonName}BV");

        try
        {
            var newPhsyicsObject = PhysicsObjectGenerator.GeneratePhysicsObject(skeleton, collisionObject, false);
            var newPhsyicsObjectBV = collisionObjectBV == null ? null : PhysicsObjectGenerator.GeneratePhysicsObject(skeletonBV, collisionObjectBV, true);

            var oldPhysicsObject = p3dFile.GetFirstChunkOfType<PhysicsObjectChunk>(carName);
            if (oldPhysicsObject != null)
            {
                if (RemoveExisting)
                    p3dFile.Chunks.Remove(oldPhysicsObject);
                else
                    oldPhysicsObject.Name += "_old";
            }

            var oldPhysicsObjectBV = p3dFile.GetFirstChunkOfType<PhysicsObjectChunk>($"{carName}BV");
            if (oldPhysicsObjectBV != null)
            {
                if (RemoveExisting)
                    p3dFile.Chunks.Remove(oldPhysicsObjectBV);
                else
                    oldPhysicsObjectBV.Name += "_old";
            }

            if (AddHistoryChunk)
                p3dFile.Chunks.Add(new HistoryChunk([$"Physics Objects Generated by Car Physics Object Generator Pure3D Data Viewer Plugin v{Assembly.GetExecutingAssembly().GetName().Version}.", $"Remove Existing: {RemoveExisting}", $"Run at {DateTime.Now:R}"]));
            p3dFile.Chunks.Add(newPhsyicsObject);
            if (newPhsyicsObjectBV != null)
                p3dFile.Chunks.Add(newPhsyicsObjectBV);

            return FileCallbackResult.Modified;
        }
        catch (Exception ex)
        {
            MessageBox.Show($"There was an error generating the physics object. Nothing changed.\n\n{ex.Message}", Name, MessageBoxButtons.OK, MessageBoxIcon.Error);
            return FileCallbackResult.Unchanged;
        }
    }

    public bool IsFileSupported(P3DFile p3dFile)
    {
        var compositeDrawables = p3dFile.GetChunksOfType<CompositeDrawableChunk>();
        if (compositeDrawables.Count == 0)
            return false;

        if (compositeDrawables.Count > 1)
            return true;

        CompositeDrawableChunk compositeDrawable = compositeDrawables[0];
        var skeletonName = compositeDrawable.SkeletonName;

        var skeleton = p3dFile.GetFirstChunkOfType<SkeletonChunk>(skeletonName);
        if (skeleton == null)
            return false;

        var collisionObject = p3dFile.GetFirstChunkOfType<CollisionObjectChunk>(skeletonName);
        if (collisionObject == null)
            return false;

        return true;
    }
}
