<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWindowsForms>true</UseWindowsForms>
	<Title>Import/Export Texture Pure3D Data Viewer Plugin</Title>
	<Authors>Proddy</Authors>
	<Company>Donut Team</Company>
	<Product>Pure3D Data Viewer</Product>
	<Description>A plugin for the Pure3D Data Viewer to allow importing and exporting of textures.</Description>
	<Copyright>Donut Team 2025</Copyright>
	<PlatformTarget>x64</PlatformTarget>
	<SelfContained>false</SelfContained>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ExportTheme_16x.png" />
    <None Remove="ImportTheme_16x.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ExportTheme_16x.png" />
    <EmbeddedResource Include="ImportTheme_16x.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pure3DDataViewerPluginAPI\Pure3DDataViewerPluginAPI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Editors\Controls\ViewTextureEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Editors\Controls\ViewImageEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if &quot;$(SolutionDir)&quot;==&quot;*Undefined*&quot; exit /b 0&#xD;&#xA;&#xD;&#xA;mkdir &quot;$(SolutionDir)Pure3DDataViewer\bin\$(Configuration)\net8.0-windows\win-x64\Plugins&quot;&#xD;&#xA;copy /Y &quot;$(TargetPath)&quot; &quot;$(SolutionDir)Pure3DDataViewer\bin\$(Configuration)\net8.0-windows\win-x64\Plugins\$(TargetFileName)&quot;&#xD;&#xA;copy /Y &quot;$([System.IO.Path]::ChangeExtension($(TargetPath), '.pdb'))&quot; &quot;$(SolutionDir)Pure3DDataViewer\bin\$(Configuration)\net8.0-windows\win-x64\Plugins\$([System.IO.Path]::ChangeExtension($(TargetFileName), '.pdb'))&quot;&#xA;" />
  </Target>

</Project>
